### ISSUE TITLE
Adding a 'TowTruckVehicles' variable under 'service variables' in config_cl.lua

### ISSUE THREAD

**Issue by jackjordan12** [xSilvermanx/PD5M#20]
This would be very similar to:
`CoronerVehicles = {"policet"}`

Something like this:
`TowTruckVehicles = {"flatbed"}`

I know that this can be done on line 94 of /service/tow_cl.lua, but it would be nice to have this in the config too.

**Comment by xSilvermanx** [comment]
This is very much intended since I do not plan to have the towtruck replaceable. Reason is that I'd like to have the towtrucks with hooks useable for AI as well. Having the towtrucks configurable would mean serious coding to make sure that the replacements actually work for the AI. Else crashes might happen.
